//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.21 at 12:43:58 AM CEST 
//


package com.dr.books;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dr.books package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dr.books
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteBookDetailResponse }
     * 
     */
    public DeleteBookDetailResponse createDeleteBookDetailResponse() {
        return new DeleteBookDetailResponse();
    }

    /**
     * Create an instance of {@link GetBookDetailResponse }
     * 
     */
    public GetBookDetailResponse createGetBookDetailResponse() {
        return new GetBookDetailResponse();
    }

    /**
     * Create an instance of {@link BookDetails }
     * 
     */
    public BookDetails createBookDetails() {
        return new BookDetails();
    }

    /**
     * Create an instance of {@link GetAllBookDetailRequest }
     * 
     */
    public GetAllBookDetailRequest createGetAllBookDetailRequest() {
        return new GetAllBookDetailRequest();
    }

    /**
     * Create an instance of {@link GetAllBookDetailResponse }
     * 
     */
    public GetAllBookDetailResponse createGetAllBookDetailResponse() {
        return new GetAllBookDetailResponse();
    }

    /**
     * Create an instance of {@link GetBookDetailRequest }
     * 
     */
    public GetBookDetailRequest createGetBookDetailRequest() {
        return new GetBookDetailRequest();
    }

    /**
     * Create an instance of {@link DeleteBookDetailRequest }
     * 
     */
    public DeleteBookDetailRequest createDeleteBookDetailRequest() {
        return new DeleteBookDetailRequest();
    }

}
