//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.21 at 12:43:58 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dr.com/books", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dr.books;
